language: r
r:
  - release
sudo: false
warnings_are_errors: false
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - plyr
  - pbapply
  - pROC
  - caret

before_install:
  - R -e 'install.packages("remotes")'
install:
  - R -e 'remotes::install_deps(dep = NA)'
