language: r
warnings_are_errors: false
cache: packages
r:
  - oldrel
  - release
  - devel
env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: false
r_binary_packages: ada, ANTsR, arm, bartMachine, base64enc, caret, cluster, C50, data.tree, deepnet, dendextend (>= 0.18.0), doParallel, d3heatmap, earth, EMCluster, extraTrees, evtree, e1071, fastICA, flexclust, FNN, foreach, fpc, gamsel, gbm, gbm3, ggplot2, glmnet, GPArotation, grid, gsubfn, heatmaply, hopach, htmlwidgets, h2o, ica, imager, inTrees, iRF, keras, kernlab, lars, lavaan, leaps, lle, MASS, mda, mgcv, missForest, mxnet, nlme, nnet, NMF, np, nsprcomp, oro.nifti, partykit, pbapply, plotly, polspline, PPtree, pROC, psych, PMA, png, plyr, pvclust, qrnn, randomForest, randomForestSRC, ranger, rCUR, RColorBrewer, RNifti, ROCR, rpart, rpart.plot, rstudioapi, Rtsne, R.utils, scales (>= 0.2.5), sgd, snow, snowfall, sparklyr, splines2, spls, survival, tgp, vegan, xgboost, knitr, rmarkdown, uwot

install:
- R -e 'remotes::install_deps(dep = FALSE)'
