language: r
r:
  - release
sudo: false
warnings_are_errors: false
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - R -e 'install.packages(c("remotes", "plyr", "pbapply", "pROC", "caret", "ranger", "rpart", "data.tree"))'

install:
  - R -e 'remotes::install_deps(dep = NA)'
